// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectNS.Data;

namespace ProjectNotisphare.Migrations.NSDb
{
    [DbContext(typeof(NSDbContext))]
    [Migration("20220502181016_Intial")]
    partial class Intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectNS.Model.FDAClassification", b =>
                {
                    b.Property<int>("FDAClassificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FdaClassificationName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("FDAClassificationId");

                    b.ToTable("FDAClassification");
                });

            modelBuilder.Entity("ProjectNS.Model.RecallCategories", b =>
                {
                    b.Property<int>("RecallCategoriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RecallCategoriesName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("RecallInfoId")
                        .HasColumnType("int");

                    b.HasKey("RecallCategoriesId");

                    b.HasIndex("RecallInfoId");

                    b.ToTable("RecallCategories");
                });

            modelBuilder.Entity("ProjectNS.Model.RecallInfo", b =>
                {
                    b.Property<int>("RecallInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CustomizeedContent")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FDAClassification")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("MarkAsUrgent")
                        .HasColumnType("bit");

                    b.Property<string>("RecallCategories")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RecallDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecallId")
                        .HasColumnType("int");

                    b.Property<string>("RecallName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RecallStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RecallType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SupplierVoluntaryRegulatoryMandate")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SupportingMaterial")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ZNumber")
                        .HasColumnType("int");

                    b.HasKey("RecallInfoId");

                    b.ToTable("RecallInfo");
                });

            modelBuilder.Entity("ProjectNS.Model.RecallType", b =>
                {
                    b.Property<int>("RecallTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RecallTypeName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RecallTypeId");

                    b.ToTable("RecallType");
                });

            modelBuilder.Entity("ProjectNS.Model.RecallCategories", b =>
                {
                    b.HasOne("ProjectNS.Model.RecallInfo", "RecallInfo")
                        .WithMany("RecallCategorieas")
                        .HasForeignKey("RecallInfoId");

                    b.Navigation("RecallInfo");
                });

            modelBuilder.Entity("ProjectNS.Model.RecallInfo", b =>
                {
                    b.Navigation("RecallCategorieas");
                });
#pragma warning restore 612, 618
        }
    }
}
